[project]
name = "renovate-37344-reproduction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.6"
dependencies = [
    "opentelemetry-sdk>=1.33.0",
]
